name: Deploy to Server

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Update Server Repo
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      with:
        args: |
          cd repo
          git clone https://github.com/awscloude/test-ec2.git
          cd test-ec2
          ls
          echo "tet done"
        
