name: Deploy to EC2 with Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- run: npm install
      shell: bash
    - uses: tzzs/server-shell@v3
      with:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}
        USERNAME: ${{secrets.USERNAME}}
        IP: ${{secrets.IP}}
        PORT: ${{secrets.PORT}}
        SHELL: |
          "echo action-test"
          "ls"
