name: Deploy to EC2 with Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Execute Deployment Script
        run: |
          chmod +x e2-connect.sh
          ./e2-connect.sh
